[near_rpc]
# rpc_endpoint = "https://rpc.testnet.near.org"
rpc_endpoint = "https://endpoints.omniatech.io/v1/near/testnet/public"

[state_data]
data_folder = "./tmp/chain_data/testnet"
# to cache about 1 hours' data
max_cached_heights = 3600
